# Generated by Django 4.2 on 2023-05-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transaction_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
